#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/m14x

PRODUCT_COPY_FILES += \
    vendor/samsung/m14x/proprietary/odm/etc/selinux/precompiled_sepolicy:$(TARGET_COPY_OUT_ODM)/etc/selinux/precompiled_sepolicy \
    vendor/samsung/m14x/proprietary/odm/etc/selinux/precompiled_sepolicy.plat_sepolicy_and_mapping.sha256:$(TARGET_COPY_OUT_ODM)/etc/selinux/precompiled_sepolicy.plat_sepolicy_and_mapping.sha256 \
    vendor/samsung/m14x/proprietary/odm/etc/selinux/precompiled_sepolicy.system_ext_sepolicy_and_mapping.sha256:$(TARGET_COPY_OUT_ODM)/etc/selinux/precompiled_sepolicy.system_ext_sepolicy_and_mapping.sha256 \
    vendor/samsung/m14x/proprietary/vendor/bin/hw/android.hardware.gatekeeper@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gatekeeper@1.0-service \
    vendor/samsung/m14x/proprietary/vendor/etc/SoundBoosterParam.txt:$(TARGET_COPY_OUT_VENDOR)/etc/SoundBoosterParam.txt \
    vendor/samsung/m14x/proprietary/vendor/etc/a2dpsink_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/a2dpsink_audio_policy_configuration.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/audio_board_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_board_info.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/audio_effects_sec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects_sec.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/audio_effects_spatializer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects_spatializer.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/audio_policy_configuration_base.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration_base.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/audio_policy_configuration_sec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration_sec.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/audio_policy_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_volumes.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/beauty/settings.dat:$(TARGET_COPY_OUT_VENDOR)/etc/beauty/settings.dat \
    vendor/samsung/m14x/proprietary/vendor/etc/bluetooth/bt_did.conf:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/bt_did.conf \
    vendor/samsung/m14x/proprietary/vendor/etc/bluetooth_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_audio_policy_configuration.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/btcon.json:$(TARGET_COPY_OUT_VENDOR)/etc/btcon.json \
    vendor/samsung/m14x/proprietary/vendor/etc/dax3_media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dax3_media_codecs_dolby_audio.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/default_volume_tables.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default_volume_tables.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/dpolicy:$(TARGET_COPY_OUT_VENDOR)/etc/dpolicy \
    vendor/samsung/m14x/proprietary/vendor/etc/ems.json:$(TARGET_COPY_OUT_VENDOR)/etc/ems.json \
    vendor/samsung/m14x/proprietary/vendor/etc/ems_parameter.json:$(TARGET_COPY_OUT_VENDOR)/etc/ems_parameter.json \
    vendor/samsung/m14x/proprietary/vendor/etc/epic.json:$(TARGET_COPY_OUT_VENDOR)/etc/epic.json \
    vendor/samsung/m14x/proprietary/vendor/etc/floating_feature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/floating_feature.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/fstab.ramplus:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ramplus \
    vendor/samsung/m14x/proprietary/vendor/etc/fstab.s5e8535:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.s5e8535 \
    vendor/samsung/m14x/proprietary/vendor/etc/gnss/ca.pem:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/ca.pem \
    vendor/samsung/m14x/proprietary/vendor/etc/gnss/deleteLogCommands:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/deleteLogCommands \
    vendor/samsung/m14x/proprietary/vendor/etc/gnss/gps.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.cfg \
    vendor/samsung/m14x/proprietary/vendor/etc/gnss/gps.debug.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.debug.cfg \
    vendor/samsung/m14x/proprietary/vendor/etc/gnss/gps.issuetracker.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.issuetracker.cfg \
    vendor/samsung/m14x/proprietary/vendor/etc/gnss/hardware_factors.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/hardware_factors.conf \
    vendor/samsung/m14x/proprietary/vendor/etc/gps_debug.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps_debug.conf \
    vendor/samsung/m14x/proprietary/vendor/etc/hearing_aid_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/hearing_aid_audio_policy_configuration.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/hqm_device.xml:$(TARGET_COPY_OUT_VENDOR)/etc/hqm_device.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/hyper/config_chipset.json:$(TARGET_COPY_OUT_VENDOR)/etc/hyper/config_chipset.json \
    vendor/samsung/m14x/proprietary/vendor/etc/hyper/config_hyper_permission.json:$(TARGET_COPY_OUT_VENDOR)/etc/hyper/config_hyper_permission.json \
    vendor/samsung/m14x/proprietary/vendor/etc/hyper/config_vendor.json:$(TARGET_COPY_OUT_VENDOR)/etc/hyper/config_vendor.json \
    vendor/samsung/m14x/proprietary/vendor/etc/init.insmod.s5e8535.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/init.insmod.s5e8535.cfg \
    vendor/samsung/m14x/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/android.hardware.drm-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.widevine.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/android.hardware.media.omx@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.omx@1.0-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/android.hardware.usb@1.3-service.coral.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb@1.3-service.coral.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/android.hardware.wifi.supplicant-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi.supplicant-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/android.hardware.wifi@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi@1.0-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/boringssl_self_test.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/boringssl_self_test.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/camera.unihal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camera.unihal.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/cass.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cass.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/dmd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dmd.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/dumpstate-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dumpstate-default.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/emservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/emservice.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/epic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/epic.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/face-default-sec.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/face-default-sec.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/fingerprint_common.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fingerprint_common.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/hyper-default-sec.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hyper-default-sec.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/init.baseband.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.baseband.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/init.fingerprint.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.fingerprint.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/init.gps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/init.ramplus.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.ramplus.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/init.s5e8535.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.s5e8535.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/init.s5e8535.usb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.s5e8535.usb.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/init.sensorhub.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.sensorhub.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/init.vendor.onebinary.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.onebinary.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/init.vendor.rilcommon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilcommon.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/init.vendor.sysfw.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.sysfw.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/lights-default-sec.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/lights-default-sec.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/pa_daemon_teegris.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pa_daemon_teegris.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/power-default-sec.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/power-default-sec.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/samsung.hardware.media.c2@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/samsung.hardware.media.c2@1.2-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/samsung.software.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/samsung.software.media.c2@1.0-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/secaudiohalaidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/secaudiohalaidl.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/snap_utility.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/snap_utility.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/snaplite_utility.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/snaplite_utility.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/teegris.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/teegris.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vaultkeeper_common.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vaultkeeper_common.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.biometrics.fingerprint-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.biometrics.fingerprint-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.gnss-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.gnss-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.health-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.health-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.securesnap-lazy.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.securesnap-lazy.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.security.drk@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.security.drk@2.0-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.security.engmode@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.security.engmode@1.0-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.security.fkeymaster-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.security.fkeymaster-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.security.skpm-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.security.skpm-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.security.widevine.keyprov-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.security.widevine.keyprov-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.snap-lazy.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.snap-lazy.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.sysinput@1.3-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.sysinput@1.3-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.thermal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.thermal@1.0-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.tlc.iccc@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.tlc.iccc@1.0-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.tlc.kg-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.tlc.kg-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.tlc.ucm@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.tlc.ucm@2.0-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.vibrator-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.vibrator-default.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.hardware.wifi@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.wifi@2.0-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.rilchip.slsi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rilchip.slsi.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rild.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor.samsung_slsi.hardware.epic@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung_slsi.hardware.epic@1.0-service.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/vendor_flash_recovery.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor_flash_recovery.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/wifi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/init/wifi_slsi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi_slsi.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/locale/plmn_delta_eng.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_eng.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/locale/plmn_delta_zh-rCN.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rCN.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/locale/plmn_delta_zh-rHK.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rHK.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/locale/plmn_delta_zh-rTW.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rTW.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/media_codecs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/media_codecs_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_c2.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/media_codecs_c2_sec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_c2_sec.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/media_codecs_c2_sec_ape.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_c2_sec_ape.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/media_codecs_c2_sec_qcp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_c2_sec_qcp.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/media_codecs_google_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_google_audio.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/media_codecs_performance.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/media_codecs_performance_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_c2.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/mercury.json:$(TARGET_COPY_OUT_VENDOR)/etc/mercury.json \
    vendor/samsung/m14x/proprietary/vendor/etc/mixer_gains.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_gains.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/mixer_usb_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_usb_default.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/mixer_usb_gray.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_usb_gray.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/mixer_usb_white.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_usb_white.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/mkshrc:$(TARGET_COPY_OUT_VENDOR)/etc/mkshrc \
    vendor/samsung/m14x/proprietary/vendor/etc/mtu-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtu-conf.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/mvno_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mvno_list.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/pdpcnt-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pdpcnt-conf.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.bluetooth.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.bluetooth.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.bluetooth_le.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.bluetooth_le.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.camera.autofocus.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.camera.autofocus.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.camera.flash-autofocus.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.camera.flash-autofocus.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.camera.front.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.camera.front.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.camera.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.hardware_keystore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.hardware_keystore.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.keystore.app_attest_key.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.keystore.app_attest_key.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.location.gps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.location.gps.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.opengles.aep.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.opengles.aep.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.sensor.accelerometer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.accelerometer.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.sensor.compass.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.compass.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.sensor.gyroscope.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.gyroscope.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.sensor.light.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.light.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.sensor.proximity.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.proximity.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.sensor.stepcounter.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.stepcounter.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.sensor.stepdetector.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.stepdetector.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.usb.accessory.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.usb.accessory.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.usb.host.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.usb.host.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.vulkan.compute.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.vulkan.compute.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.vulkan.level.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.vulkan.level.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.vulkan.version.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.vulkan.version.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.wifi.direct.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.wifi.direct.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.wifi.passpoint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.wifi.passpoint.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.hardware.wifi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.wifi.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.software.device_id_attestation.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.device_id_attestation.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.software.ipsec_tunnels.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.ipsec_tunnels.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.software.midi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.midi.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.software.opengles.deqp.level.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.opengles.deqp.level.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.software.verified_boot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.verified_boot.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/android.software.vulkan.deqp.level.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.vulkan.deqp.level.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/handheld_core_hardware.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/handheld_core_hardware.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/vendor.samsung.hardware.telephony.cdma_excluded.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor.samsung.hardware.telephony.cdma_excluded.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/vendor.samsung.hardware.telephony.gsm.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor.samsung.hardware.telephony.gsm.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/permissions/vendor.samsung.hardware.telephony.satellite.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor.samsung.hardware.telephony.satellite.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/plmn_delta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/plmn_delta_attaio.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_attaio.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/plmn_delta_hktw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_hktw.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/plmn_delta_ltn.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_ltn.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/plmn_delta_usagsm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usagsm.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/plmn_se13_prebuilt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13_prebuilt.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/samsung/m14x/proprietary/vendor/etc/r_submix_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/r_submix_audio_policy_configuration.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/saiv/gae/MeanFea.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/MeanFea.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/saiv/gae/ParaFea.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/ParaFea.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/saiv/gae/PmAgeFeatSelIdx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmAgeFeatSelIdx.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/saiv/gae/PmAgeModel.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmAgeModel.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/saiv/gae/PmExpFeatSelIdx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmExpFeatSelIdx.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/saiv/gae/PmExpModel.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmExpModel.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/saiv/gae/PmGenModel.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmGenModel.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/saiv/gae/PmGenderFeatSelIdx.bin:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/gae/PmGenderFeatSelIdx.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/saiv/image_understanding/db/aic_classifier/aic_classifier_cnn.info:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/image_understanding/db/aic_classifier/aic_classifier_cnn.info \
    vendor/samsung/m14x/proprietary/vendor/etc/saiv/image_understanding/db/aic_classifier/aic_classifier_cnn_light.caffemodel:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/image_understanding/db/aic_classifier/aic_classifier_cnn_light.caffemodel \
    vendor/samsung/m14x/proprietary/vendor/etc/saiv/image_understanding/db/aic_detector/aic_detector_cnn.info:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/image_understanding/db/aic_detector/aic_detector_cnn.info \
    vendor/samsung/m14x/proprietary/vendor/etc/saiv/image_understanding/db/aic_detector/aic_detector_cnn_light.caffemodel:$(TARGET_COPY_OUT_VENDOR)/etc/saiv/image_understanding/db/aic_detector/aic_detector_cnn_light.caffemodel \
    vendor/samsung/m14x/proprietary/vendor/etc/sec_audio_volume_curve.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sec_audio_volume_curve.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/seccomp_policy/codec2.vendor.base.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.base.policy \
    vendor/samsung/m14x/proprietary/vendor/etc/seccomp_policy/codec2.vendor.ext.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.ext.policy \
    vendor/samsung/m14x/proprietary/vendor/etc/seccomp_policy/mediaextractor_sec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor_sec.policy \
    vendor/samsung/m14x/proprietary/vendor/etc/seccomp_policy/samsung.software.media.c2-base-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/samsung.software.media.c2-base-policy \
    vendor/samsung/m14x/proprietary/vendor/etc/seccomp_policy/samsung.software.media.c2-ext-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/samsung.software.media.c2-ext-policy \
    vendor/samsung/m14x/proprietary/vendor/etc/selinux/plat_pub_versioned.cil:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/plat_pub_versioned.cil \
    vendor/samsung/m14x/proprietary/vendor/etc/selinux/plat_sepolicy_vers.txt:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/plat_sepolicy_vers.txt \
    vendor/samsung/m14x/proprietary/vendor/etc/selinux/selinux_denial_metadata:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/selinux_denial_metadata \
    vendor/samsung/m14x/proprietary/vendor/etc/selinux/sk/authorize.xml:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/sk/authorize.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/selinux/vendor_file_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_file_contexts \
    vendor/samsung/m14x/proprietary/vendor/etc/selinux/vendor_hwservice_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_hwservice_contexts \
    vendor/samsung/m14x/proprietary/vendor/etc/selinux/vendor_mac_permissions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_mac_permissions.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/selinux/vendor_property_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_property_contexts \
    vendor/samsung/m14x/proprietary/vendor/etc/selinux/vendor_seapp_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_seapp_contexts \
    vendor/samsung/m14x/proprietary/vendor/etc/selinux/vendor_sepolicy.cil:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_sepolicy.cil \
    vendor/samsung/m14x/proprietary/vendor/etc/selinux/vendor_sepolicy_version:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_sepolicy_version \
    vendor/samsung/m14x/proprietary/vendor/etc/selinux/vendor_service_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_service_contexts \
    vendor/samsung/m14x/proprietary/vendor/etc/selinux/vndservice_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vndservice_contexts \
    vendor/samsung/m14x/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/samsung/m14x/proprietary/vendor/etc/situation_audio_policy_volumes_sec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/situation_audio_policy_volumes_sec.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/snap_gpu_kernel_64.bin:$(TARGET_COPY_OUT_VENDOR)/etc/snap_gpu_kernel_64.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/snaplite_cache.bin:$(TARGET_COPY_OUT_VENDOR)/etc/snaplite_cache.bin \
    vendor/samsung/m14x/proprietary/vendor/etc/somxreg.conf:$(TARGET_COPY_OUT_VENDOR)/etc/somxreg.conf \
    vendor/samsung/m14x/proprietary/vendor/etc/sound_trigger_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_info.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/str/str_preference_data.dat:$(TARGET_COPY_OUT_VENDOR)/etc/str/str_preference_data.dat \
    vendor/samsung/m14x/proprietary/vendor/etc/sysconfig/vendor-apex-allowlist.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sysconfig/vendor-apex-allowlist.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/task_profiles.json:$(TARGET_COPY_OUT_VENDOR)/etc/task_profiles.json \
    vendor/samsung/m14x/proprietary/vendor/etc/traceconfig.txt:$(TARGET_COPY_OUT_VENDOR)/etc/traceconfig.txt \
    vendor/samsung/m14x/proprietary/vendor/etc/ueventd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/ueventd.rc \
    vendor/samsung/m14x/proprietary/vendor/etc/usb_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usb_audio_policy_configuration.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/vramdiskd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vramdiskd.xml \
    vendor/samsung/m14x/proprietary/vendor/etc/wifi/indoorchannel.info:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/indoorchannel.info \
    vendor/samsung/m14x/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/samsung/m14x/proprietary/vendor/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/m14x/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/samsung/m14x/proprietary/vendor/etc/wlan_common_rc:$(TARGET_COPY_OUT_VENDOR)/etc/wlan_common_rc \
    vendor/samsung/m14x/proprietary/vendor/etc/wlan_vendor_rc:$(TARGET_COPY_OUT_VENDOR)/etc/wlan_vendor_rc \
    vendor/samsung/m14x/proprietary/vendor/firmware/APDV_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APDV_AUDIO_SLSI.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/AP_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/AP_AUDIO_SLSI.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/OD_V2.4.2_06_30_QVGA_RICE_VRA_RGB1P.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V2.4.2_06_30_QVGA_RICE_VRA_RGB1P.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/OD_V2.5.1_06_30_VGA_RICE_VRA_RGB1P.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V2.5.1_06_30_VGA_RICE_VRA_RGB1P.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/SetMultiCalInfo.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SetMultiCalInfo.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/SoundAlive.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SoundAlive.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/SoundBoosterParam.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SoundBoosterParam.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/a2dpcom.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a2dpcom.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/abov/a96t396_m14x_main.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/abov/a96t396_m14x_main.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/abov/a96t396_m14x_sub.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/abov/a96t396_m14x_sub.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/abox_solution.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_solution.conf \
    vendor/samsung/m14x/proprietary/vendor/firmware/abox_system.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_system.conf \
    vendor/samsung/m14x/proprietary/vendor/firmware/abox_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/abox_tplg.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.conf \
    vendor/samsung/m14x/proprietary/vendor/firmware/avsyncmix.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/avsyncmix.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/calliope_dram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_dram.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/calliope_sram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_sram.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/camera_tilt_calibration_info_1_4:$(TARGET_COPY_OUT_VENDOR)/firmware/camera_tilt_calibration_info_1_4 \
    vendor/samsung/m14x/proprietary/vendor/firmware/cs40l26.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26.wmfw \
    vendor/samsung/m14x/proprietary/vendor/firmware/dax_param.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dax_param.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/default_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/default_configuration.flm.cfg.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/dolby.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dolby.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/ft8720_m14x.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ft8720_m14x.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/ft8720_m14x_ramtest.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ft8720_m14x_ramtest.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/listenbackeffect.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/listenbackeffect.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/nt36672_m14x_csot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36672_m14x_csot.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/nt36672_m14x_csot_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36672_m14x_csot_mp.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/os.checked.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/pablo_icpufw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/pablo_icpufw.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/rxse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/rxse.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/sb_ll.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_ll.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/sb_music.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_music.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/sb_others.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_others.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/sectiongraph_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sectiongraph_tplg.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/sectiongraph_tplg.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/sectiongraph_tplg.conf \
    vendor/samsung/m14x/proprietary/vendor/firmware/secure_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/secure_configuration.flm.cfg.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/setfile_3l6.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_3l6.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/setfile_gc02m1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_gc02m1.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/setfile_gc02m2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_gc02m2.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/setfile_hi1336.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_hi1336.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/setfile_jn1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_jn1.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/setfile_sc201.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_sc201.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/setfile_sc201_macro.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_sc201_macro.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/spkamp_sma1305.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/spkamp_sma1305.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/txse1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/txse1.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/txse2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/txse2.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/volumemonitor.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/volumemonitor.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/hydra_config.sdb:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/hydra_config.sdb \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/build_id.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/build_id.txt \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/bt/log-strings.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/bt/log-strings.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/common/log-strings.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/common/log-strings.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_dbg.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_dbg.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_dwt.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_dwt.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_etm.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_etm.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_fpb.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_fpb.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_itm.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_itm.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_mpu.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_mpu.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_nvic.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_nvic.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_scs.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_scs.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_tpi.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM3_tpi.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_dbg.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_dbg.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_dwt.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_dwt.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_fpb.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_fpb.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_itm.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_itm.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_mpu.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_mpu.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_nvic.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_nvic.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_scs.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexM7_scs.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/cortexR7.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/cortexR7.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/m3_periph_dwt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/m3_periph_dwt_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/m3_periph_fpb_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/m3_periph_fpb_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/m3_periph_itm_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/m3_periph_itm_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/m3_periph_nvic_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/m3_periph_nvic_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/mb_ap2bt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/mb_ap2bt_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/mb_ap2wl_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/mb_ap2wl_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/mb_apm2wlbt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/mb_apm2wlbt_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/mb_cp2bt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/mb_cp2bt_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/mb_cp2wl_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/mb_cp2wl_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/mb_gnss2wlbt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/mb_gnss2wlbt_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/mb_wlbt2abox_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/mb_wlbt2abox_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/mb_wlbt2chub_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/mb_wlbt2chub_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/moredump.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/moredump.bin \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/moredump.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/moredump.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/moredump/rf_chip_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/moredump/rf_chip_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/moredump64.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/moredump64.txt \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/perb_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/perb_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/peri_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/peri_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/periph_gic_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/periph_gic_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/periph_int_ifc_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/periph_int_ifc_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/periph_scu_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/periph_scu_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pert_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pert_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/perw_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/perw_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu/moredump/pmu_peri_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu/moredump/pmu_peri_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu_8051/pmu_peri/moredump/pmu_peri_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu_8051/pmu_peri/moredump/pmu_peri_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu_conf/pmu_conf/moredump/pmu_conf_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu_conf/pmu_conf/moredump/pmu_conf_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu_conf_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu_conf_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pmu_peri_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pmu_peri_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_ap2bt/moredump/mb_ap2bt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_ap2bt/moredump/mb_ap2bt_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_ap2wl/moredump/mb_ap2wl_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_ap2wl/moredump/mb_ap2wl_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_apm2wlbt/moredump/mb_apm2wlbt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_apm2wlbt/moredump/mb_apm2wlbt_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_cp2bt/moredump/mb_cp2bt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_cp2bt/moredump/mb_cp2bt_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_cp2wl/moredump/mb_cp2wl_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_cp2wl/moredump/mb_cp2wl_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_gnss2wlbt/moredump/mb_gnss2wlbt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_gnss2wlbt/moredump/mb_gnss2wlbt_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_wlbt2abox/moredump/mb_wlbt2abox_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_wlbt2abox/moredump/mb_wlbt2abox_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_wlbt2chub/moredump/mb_wlbt2chub_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/mb_wlbt2chub/moredump/mb_wlbt2chub_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/peri/moredump/peri_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/peri/moredump/peri_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/periph_gic/moredump/periph_gic_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/periph_gic/moredump/periph_gic_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/periph_int_ifc/moredump/periph_int_ifc_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/periph_int_ifc/moredump/periph_int_ifc_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/periph_scu/moredump/periph_scu_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/periph_scu/moredump/periph_scu_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/pert/moredump/pert_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/pert/moredump/pert_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/pp/perw_pri/moredump/perw_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/pp/perw_pri/moredump/perw_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/rf_chip_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/rf_chip_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_dwt/moredump/m3_periph_dwt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_dwt/moredump/m3_periph_dwt_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_fpb/moredump/m3_periph_fpb_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_fpb/moredump/m3_periph_fpb_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_itm/moredump/m3_periph_itm_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_itm/moredump/m3_periph_itm_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_nvic/moredump/m3_periph_nvic_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/m3_periph_nvic/moredump/m3_periph_nvic_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_ap2bt/moredump/mb_ap2bt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_ap2bt/moredump/mb_ap2bt_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_ap2wl/moredump/mb_ap2wl_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_ap2wl/moredump/mb_ap2wl_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_apm2wlbt/moredump/mb_apm2wlbt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_apm2wlbt/moredump/mb_apm2wlbt_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_cp2bt/moredump/mb_cp2bt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_cp2bt/moredump/mb_cp2bt_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_cp2wl/moredump/mb_cp2wl_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_cp2wl/moredump/mb_cp2wl_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_gnss2wlbt/moredump/mb_gnss2wlbt_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_gnss2wlbt/moredump/mb_gnss2wlbt_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_wlbt2abox/moredump/mb_wlbt2abox_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_wlbt2abox/moredump/mb_wlbt2abox_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_wlbt2chub/moredump/mb_wlbt2chub_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/mb_wlbt2chub/moredump/mb_wlbt2chub_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/perb/moredump/perb_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/perb/moredump/perb_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/pert/moredump/pert_registers.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/hardware/moredump/wpanpp/pert/moredump/pert_registers.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/wlan/hip_signals.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/hip_signals.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/wlan/hydra_config.sdb:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/hydra_config.sdb \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/wlan/id.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/id.txt \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/wlan/mib_out.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/mib_out.xml \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/wlan/symbols.dbg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/symbols.dbg \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/wlan/unicli.dbg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/unicli.dbg \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/wlan/unitab.dbg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/unitab.dbg \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/wlan/univif.dbg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/univif.dbg \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140/debug/wlan/xide_mib.dbg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/debug/wlan/xide_mib.dbg \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140_bt.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_bt.hcf \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140_common.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_common.hcf \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140_wlan.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan.hcf \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140_wlan_sw.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan_sw.hcf \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140_wlan_t.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan_t.hcf \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/mx140_wlan_t_sw.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan_t_sw.hcf \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/platform.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/platform.txt \
    vendor/samsung/m14x/proprietary/vendor/firmware/wifi/slsi_reg_database.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/slsi_reg_database.bin \
    vendor/samsung/m14x/proprietary/vendor/recovery-from-boot.p:$(TARGET_COPY_OUT_VENDOR)/recovery-from-boot.p \
    vendor/samsung/m14x/proprietary/vendor/saiv/image_understanding/db/aig_classifier/aig_classifier_cnn.tf:$(TARGET_COPY_OUT_VENDOR)/saiv/image_understanding/db/aig_classifier/aig_classifier_cnn.tf \
    vendor/samsung/m14x/proprietary/vendor/saiv/image_understanding/db/aig_detector/aig_detector_cnn.tflite:$(TARGET_COPY_OUT_VENDOR)/saiv/image_understanding/db/aig_detector/aig_detector_cnn.tflite \
    vendor/samsung/m14x/proprietary/vendor/saiv/image_understanding/db/srr_interaction/srr_interaction_cnn.tflite:$(TARGET_COPY_OUT_VENDOR)/saiv/image_understanding/db/srr_interaction/srr_interaction_cnn.tflite \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-000000534b4d:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-000000534b4d \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-000048444350:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-000048444350 \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-0000534b504d:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-0000534b504d \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-0050524f4341:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-0050524f4341 \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-0053545354ab:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-0053545354ab \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-00575644524d:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-00575644524d \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-42494f535542:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-42494f535542 \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-46494e474502:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-46494e474502 \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-4662436b6d52:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-4662436b6d52 \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-474154454b45:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-474154454b45 \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-4b45594d5354:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-4b45594d5354 \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-505256544545:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-505256544545 \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-5345435f4652:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-5345435f4652 \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-564c544b5052:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-564c544b5052 \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-656e676d6f64:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-656e676d6f64 \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-657365636f6d:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-657365636f6d \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-6b6e78677564:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-6b6e78677564 \
    vendor/samsung/m14x/proprietary/vendor/tee/00000000-0000-0000-0000-6d73745f5441:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-6d73745f5441 \
    vendor/samsung/m14x/proprietary/vendor/tee/driver/00000000-0000-0000-0000-494363447256:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-0000-0000-0000-494363447256 \
    vendor/samsung/m14x/proprietary/vendor/tee/driver/00000000-0000-0000-0000-4d53546d7374:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-0000-0000-0000-4d53546d7374 \
    vendor/samsung/m14x/proprietary/vendor/tee/driver/00000000-0000-0000-0000-53626f786476:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-0000-0000-0000-53626f786476 \
    vendor/samsung/m14x/proprietary/vendor/tee/driver/00000000-0000-0000-0000-564c544b4456:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-0000-0000-0000-564c544b4456 \
    vendor/samsung/m14x/proprietary/vendor_dlkm/lib/modules/input_booster_lkm.ko:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/input_booster_lkm.ko \
    vendor/samsung/m14x/proprietary/vendor_dlkm/lib/modules/modules.alias:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.alias \
    vendor/samsung/m14x/proprietary/vendor_dlkm/lib/modules/modules.dep:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.dep \
    vendor/samsung/m14x/proprietary/vendor_dlkm/lib/modules/modules.load:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.load \
    vendor/samsung/m14x/proprietary/vendor_dlkm/lib/modules/modules.softdep:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.softdep \
    vendor/samsung/m14x/proprietary/vendor/lib64/libhyper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhyper.so \
    vendor/samsung/m14x/proprietary/vendor/lib/libuuid.so:$(TARGET_COPY_OUT_VENDOR)/lib/libuuid.so \
    vendor/samsung/m14x/proprietary/vendor/lib64/libuuid.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libuuid.so

PRODUCT_PACKAGES += \
    android.hardware.audio.common@7.0-enums \
    android.media.audio.common.types-V1-cpp \
    arm.graphics-V1-ndk \
    libGLES_mali \
    gnss_aidl_lib \
    android.hardware.graphics.allocator@4.0-impl \
    android.hardware.graphics.mapper@4.0-impl \
    audio.bluetooth.default \
    audio.primary.s5e8535 \
    audio.sec_primary.default \
    gatekeeper.s5e8535 \
    hwcomposer.s5e8535 \
    vendor.samsung.hardware.audio@1.0-impl \
    vendor.samsung_slsi.hardware.epic@1.0-impl \
    vulkan.mali \
    libBeauty_v4.camera.samsung \
    libDualCamBokehCapture.camera.samsung \
    libExynosC2ComponentStore \
    libExynosC2H264Dec \
    libExynosC2H264Enc \
    libExynosC2HevcDec \
    libExynosC2HevcEnc \
    libExynosC2Vp8Dec \
    libExynosC2Vp8Enc \
    libExynosHWCService \
    libFaceService \
    libFace_Landmark_API.camera.samsung \
    libHprFace_GAE_api.camera.samsung \
    libHpr_RecGAE_cvFeature_v1.0.camera.samsung \
    libLocalTM_capture_core.camera.samsung \
    libLocalTM_wrapper.camera.samsung \
    libOpenCv.camera.samsung \
    libSEF.quram \
    libSamsungPostProcessConvertor \
    lib_SamsungRec_07010 \
    lib_SoundAlive_3DPosition_ver202 \
    lib_SoundAlive_AlbumArt_ver105 \
    lib_SoundAlive_SRC384_ver320 \
    lib_SoundAlive_play_plus_ver500 \
    lib_SoundBooster_ver1100 \
    lib_soundaliveresampler \
    lib_supernight_interface \
    libaboxpcmdump \
    libacryl \
    libalsautils_sec \
    libarcsoft_super_night_raw \
    libaudio-ril \
    libaudioparamupdate \
    libaudioproxy2 \
    libbeautyshot.arcsoft \
    libdatamod \
    libdrmresource \
    libegis_fp_normal_sensor_test \
    libeis_core \
    libepic_helper \
    libepicoperator \
    libexynosdisplay \
    libexynosgraphicbuffer \
    libexynosutils \
    libexynosv4l2 \
    libface_landmark.arcsoft \
    libfloatingfeature \
    libgf_in_system_lib \
    libgiantmscl \
    libgpudataproducer \
    libhwjpeg \
    libhypermotion_core \
    libhypermotion_interface \
    libhypervintf \
    libion_exynos \
    liblastaboxmsg \
    liblivefocus_capture_engine \
    liblivefocus_capture_interface \
    liblivefocus_preview_engine \
    liblivefocus_preview_interface \
    libmpbase \
    liboemservice \
    libpadm \
    libprofileparamstorage \
    libqfp_sensortest \
    librecordalive \
    libsavsac \
    libsavscmn \
    libsavsvc \
    libsecaudiocoreutils \
    libsecaudioinfo \
    libsecaudiolevel \
    libsecfr_engine \
    libsecfr_model \
    libsecnativefeature \
    libsecril-client \
    libsehbluetooth_audio_session_aidl \
    libsemnativecarrierfeature \
    libsfp_sensor \
    libsfp_teegw \
    libsnaace \
    libsnamrnb \
    libsnamrwb \
    libspatializerparamstorage \
    libspeakercalibration \
    libstagefright_foundation_vendor \
    libsynaFpSensorTestNwd \
    libteecl \
    libucm_tlc_comm \
    libucm_tlc_direct_comm \
    libucm_tlc_tz_esecomm \
    libuniplugin \
    libvdis_interface \
    libvideobeauty.arcsoft \
    libvideobeauty_interface \
    libvra \
    libwrappergps \
    mali_symlink \
    sensors.grip \
    sensors.inputvirtual \
    sensors.sensorhub \
    libaudioeffectoffload \
    libaudiosaplus_sec \
    libmyspace \
    libsamsungSoundbooster_plus \
    libswdap \
    libswspatializer \
    vendor.samsung.hardware.audio@1.0 \
    vendor.samsung.hardware.biometrics.face-V3-ndk \
    vendor.samsung.hardware.biometrics.fingerprint-V1-ndk \
    vendor.samsung.hardware.bluetooth.audio-V1-ndk \
    vendor.samsung.hardware.bluetooth.audio-impl \
    vendor.samsung.hardware.gnss-V3-ndk \
    vendor.samsung.hardware.hyper-V2-ndk \
    vendor.samsung.hardware.tlc.ucm@2.0-impl \
    vendor.samsung.hardware.tlc.ucm@2.0 \
    vendor.samsung_slsi.hardware.epic@1.0 \
    vendor.samsung_slsi.telephony.hardware.oemservice@1.0 \
    libFrucSSMLib \
    libcodecsolutionhelper_vendor \
    libpredeflicker_native \
    libstagefright_bufferqueue_helper_vendor \
    libstagefright_omx_vendor \
    libstagefright_soft_aacdec \
    libstagefright_soft_aacenc \
    libstagefright_soft_amrdec \
    libstagefright_soft_amrnbenc \
    libstagefright_soft_amrwbenc \
    libstagefright_soft_avcdec \
    libstagefright_soft_avcenc \
    libstagefright_soft_flacdec \
    libstagefright_soft_flacenc \
    libstagefright_soft_g711dec \
    libstagefright_soft_gsmdec \
    libstagefright_soft_hevcdec \
    libstagefright_soft_mp3dec \
    libstagefright_soft_mpeg2dec \
    libstagefright_soft_mpeg4dec \
    libstagefright_soft_mpeg4enc \
    libstagefright_soft_opusdec \
    libstagefright_soft_rawdec \
    libstagefright_soft_vorbisdec \
    libstagefright_soft_vpxdec \
    libstagefright_soft_vpxenc \
    vintf-codecsolution-V2-ndk \
    android.hardware.bluetooth.a2dp@1.0 \
    camera.s5e8535 \
    camera.unihal.default \
    libsecaudiohal_aidl \
    libDLInterface.camera.samsung \
    libExtIRTA \
    libIRTA \
    libSecC2ComponentStore \
    libVendorSemDataProps \
    libVendorSemTelephonyProps \
    libcodec2_sec_aacdec \
    libcodec2_sec_aacenc \
    libcodec2_sec_amrnbdec \
    libcodec2_sec_amrwbdec \
    libcodec2_sec_flacdec \
    libcodec2_sec_imadec \
    libcodec2_sec_mp3dec \
    libcodec2_sec_mp4vdec \
    libcodec2_sec_soft_common \
    libcodec2_sec_vc1dec \
    libcodec2_soft_ac4dec \
    libcodec2_soft_eac3dec \
    libcsc \
    libdeccfg \
    libdk_vnd_service_core \
    libdlrmsc \
    libdsms_vendor \
    libdualcam_refocus_image \
    libdualcam_refocus_video \
    libems_service \
    libengmode15 \
    libengmode2lite \
    libengmode_client \
    libengmode_server \
    libengmode_tlc \
    libexynos_migov \
    libexynosscaler \
    libfocuspeaking \
    libfocuspeaking.uniplugin@1.0 \
    libformatConverter.unifunc \
    libgmc \
    libhigh_dynamic_range_bokeh \
    libimgproc_sw.unifunc@common \
    liboemcrypto \
    libomp \
    libremosaic_wrapper \
    libremosaiclib \
    libril_sem \
    rild_exynos \
    lib_profiler-samsung \
    libaudioroute-samsung \
    libtinyalsa-samsung \
    libbt-exynos \
    android.hardware.bluetooth@1.0-impl-samsung \
    android.hardware.bluetooth@1.1-service.samsung \
    libsamsungcamerahal \
    libsamsungcamerahalutils \
    libsamsungcamerahwl_impl \
    libscaler_hw.unifunc \
    libscaler_sw.unifunc \
    libsec-ril \
    libsec2lsi_conversion \
    libsec_skpmHalTlc \
    libsensorlistener \
    libskeymint10device \
    libskeymint_cli \
    libsnap_compute \
    libsnap_compute_secure \
    libsnap_compute_wrapper \
    libsnap_compute_wrapper_secure \
    libsnap_vndk \
    libsnap_vndk_secure \
    libsnaplite_native \
    libsnaplite_native_secure \
    libsnaplite_wrapper \
    libsnaplite_wrapper_secure \
    libsomxcmn \
    libstork_shared \
    libtlc_comm_iccc \
    libtlc_direct_comm_iccc \
    libtvm_runtime \
    libtvm_wrapper \
    libuniapi \
    libvkmanager_vendor \
    libvkservice \
    libvpl \
    libwvaidl \
    unihal_android \
    unihal_cutils \
    unihal_entry \
    unihal_filter_unit \
    unihal_main \
    unihal_scenario \
    unihal_uniplugin@1.0 \
    vendor.samsung.frameworks.security.dsms-V1-ndk \
    vendor.samsung.hardware.audio-V1-ndk \
    vendor.samsung.hardware.bluetooth@2.0 \
    vendor.samsung.hardware.camera.device-V1-ndk \
    vendor.samsung.hardware.camera.provider-V1-ndk \
    vendor.samsung.hardware.health-V1-ndk \
    vendor.samsung.hardware.keymint-V2-ndk \
    vendor.samsung.hardware.light-V1-ndk \
    vendor.samsung.hardware.radio-V1-ndk \
    vendor.samsung.hardware.radio.bridge-V1-ndk \
    vendor.samsung.hardware.radio.channel-V1-ndk \
    vendor.samsung.hardware.radio.data-V1-ndk \
    vendor.samsung.hardware.radio.messaging-V1-ndk \
    vendor.samsung.hardware.radio.network-V1-ndk \
    vendor.samsung.hardware.radio.sim-V1-ndk \
    vendor.samsung.hardware.security.drk@2.0 \
    vendor.samsung.hardware.security.engmode@1.0 \
    vendor.samsung.hardware.security.fkeymaster-V1-ndk \
    vendor.samsung.hardware.security.skpm-V1-ndk \
    vendor.samsung.hardware.security.vaultkeeper@2.0 \
    vendor.samsung.hardware.security.widevine.keyprov-V1-ndk \
    vendor.samsung.hardware.snap-V1-ndk \
    vendor.samsung.hardware.sysinput@1.0 \
    vendor.samsung.hardware.sysinput@1.1 \
    vendor.samsung.hardware.sysinput@1.2 \
    vendor.samsung.hardware.sysinput@1.3 \
    vendor.samsung.hardware.thermal@1.0 \
    vendor.samsung.hardware.tlc.iccc@1.0-impl \
    vendor.samsung.hardware.tlc.iccc@1.0 \
    vendor.samsung.hardware.tlc.kg-V2-ndk \
    vendor.samsung.hardware.vibrator-V5-ndk \
    vendor.samsung.hardware.wifi.hostapd-V1-ndk \
    vendor.samsung.hardware.wifi.supplicant-V1-ndk \
    vendor.samsung.hardware.wifi@2.0 \
    vendor.samsung.hardware.wifi@2.1 \
    vendor.samsung.hardware.wifi@2.2 \
    vendor.samsung.hardware.wifi@2.3 \
    vendor.samsung_slsi.hardware.ExynosA2DPOffload@2.0 \
    vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0 \
    com.samsung.android.biometrics.face.signed \
    com.samsung.android.biometrics.fingerprint.signed \
    com.samsung.android.camera.unihal.signed \
    android.hardware.usb@1.3-service.coral.xml \
    android.hardware.wifi@1.0-service.xml \
    dmd.xml \
    engmode_manifest.xml \
    face-default-sec.xml \
    hyper-default-sec.xml \
    lights-default-sec.xml \
    manifest_android.hardware.drm-service.widevine.xml \
    power-samsung.xml \
    sec_c2_manifest_default0_1_2.xml \
    secaudiohalaidl_manifest.xml \
    vaultkeeper_manifest.xml \
    vendor.samsung.hardware.biometrics.fingerprint-service.xml \
    vendor.samsung.hardware.camera.provider-service.xml \
    vendor.samsung.hardware.health-service.xml \
    vendor.samsung.hardware.radio.exclude.slsi.xml \
    vendor.samsung.hardware.radio_manifest_2_33.xml \
    vendor.samsung.hardware.securesnap-default.xml \
    vendor.samsung.hardware.security.fkeymaster-service.xml \
    vendor.samsung.hardware.security.skpm-manifest.xml \
    vendor.samsung.hardware.security.widevine.keyprov-service.xml \
    vendor.samsung.hardware.sehradio_manifest_2_33.xml \
    vendor.samsung.hardware.snap-default.xml \
    vendor.samsung.hardware.thermal@1.0-manifest.xml \
    vendor.samsung.hardware.tlc.iccc@1.0-manifest.xml \
    vendor.samsung.hardware.tlc.kg-manifest.xml \
    vendor.samsung.hardware.vibrator-default.xml \
    vendor.samsung.hardware.wifi@2.0-service.xml \
    abox_log \
    add.tflite \
    cass \
    cbd \
    cld \
    dmd \
    emservice \
    enable_test_mode \
    epic \
    ffcirrus \
    fsdbg_vendor \
    android.hardware.drm-service.widevine \
    android.hardware.dumpstate-service \
    android.hardware.graphics.allocator@4.0-service \
    android.hardware.power.samsung-service \
    android.hardware.usb@1.3-service.coral \
    android.hardware.wifi@1.0-service \
    gps \
    gpsd \
    macloader \
    mfgloader \
    samsung.hardware.media.c2@1.2-service \
    samsung.software.media.c2@1.0-service \
    secaudiohalaidl \
    vendor.samsung.hardware.biometrics.face-service \
    vendor.samsung.hardware.biometrics.fingerprint-service \
    vendor.samsung.hardware.camera.provider-service_64 \
    vendor.samsung.hardware.gnss-service \
    vendor.samsung.hardware.health-service \
    vendor.samsung.hardware.hyper-service \
    vendor.samsung.hardware.light-service \
    vendor.samsung.hardware.securesnap-service \
    vendor.samsung.hardware.security.drk@2.0-service \
    vendor.samsung.hardware.security.skpm-service \
    vendor.samsung.hardware.security.widevine.keyprov-service \
    vendor.samsung.hardware.snap-service \
    vendor.samsung.hardware.sysinput@1.3-service \
    vendor.samsung.hardware.thermal@1.0-service \
    vendor.samsung.hardware.tlc.iccc@1.0-service \
    vendor.samsung.hardware.tlc.kg-service \
    vendor.samsung.hardware.tlc.ucm@2.0-service \
    vendor.samsung.hardware.vibrator-service \
    vendor.samsung.hardware.wifi@2.0-service \
    vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0-service \
    vendor.samsung_slsi.hardware.epic@1.0-service \
    init.insmod \
    install-recovery \
    iod \
    moredump \
    moredump.bin \
    mx_log_collection \
    mx_logger \
    mx_logger_dump \
    secril_config_svc \
    slsi_wlan_udi_log \
    slsi_wlan_udi_log_decode \
    snap_utility_64 \
    snaplite_utility_64 \
    test_model.json \
    tzdaemon \
    tzts_daemon \
    utility_cache_test.tflite \
    vaultkeeperd \
    vendor.samsung.hardware.security.engmode@1.0-service \
    vendor.samsung.hardware.security.fkeymaster-service \
    vendor.samsung.hardware.security.proca@2.0-service \
    vendor.samsung.hardware.security.vaultkeeper@2.0-service \
    wlbtd \
    wvkprov
